### ISSUE TITLE
leave html entities untouched, it breaks pages with weird encodings

### ISSUE THREAD

**Issue by loreb** [Y2Z/monolith#112]
Example: http://www.the-spoiler.com/RPG/New.World.Computing/might.and.magic6.3/mm6.htm
Look at the copyright, it's `"&copy;"` in the original, monolith translates that to the utf8 copyright character which is wrong because that page says `charset=iso-8859-1"` so it renders to a bogus character + the copyright sign (tested on windows/linux/openbsd).

I did meet other pages like that, this is just the one where I noticed it.

Testcase:
```
<html>
<head>
	<!-- comment out the charset to make it work !-->
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>
<body>
copyright &copy; someone
</body>
</html>
```

**Comment by snshn** [comment]
Hi Lorenzo,

Thank you very much for reporting this. It's likely the result of html5ever (the HTML parsing library we're using) treating every document as utf-8 by default and not automatically parsing that charset meta tag.

More info on the likely cause:
https://github.com/servo/html5ever/issues/18

If there's no flag available to preserve html entities, it'll likely be worth substituting those manually for non-utf8 documents upon save.

**Comment by loreb** [comment]
Ouch, a five year old bug... well, thank you for the info and the quick reply!

**Comment by snshn** [comment]
That's the next big patch I'm currently working on. What encoding is not working in your case, @moriakijp?

**Comment by snshn** [comment]
The fix is now in `master`. From what I know so far, html5ever (the HTML parser module) parses everything as Unicode, and when monolith re-assembles the document, the original information is lost, the document becomes UTF-8 no matter what charset it originally had. The current solution is to just set all meta charset tags to indicate it's a UTF-8 document. Not ideal but seems to work fine for archiving documents, even though they lose their original encoding.
