### ISSUE TITLE
Cloudflare DDOS protection

### ISSUE THREAD

**Issue by Tragen** [Y2Z/monolith#139]
With Cloudflare DDOS protected sites, I only get this screenshot.

![image](https://user-images.githubusercontent.com/1700241/77636350-42fc7a00-6f54-11ea-9a01-6269463dfe5b.png)

What can I do about that?
Could you wait for one redirect or 10 seconds and reload the page?

**Comment by snshn** [comment]
Hi there @Tragen, thank you for reporting this!

I wasn't aware of Cloudflare getting in the way of monolith, but it's only logical, since I know scrapers often bump into that page. Monolith doesn't act as a browser on its own, it rather operates by pulling assents directly (the same way curl or wget does). I'm fairly certain Cloudflare uses JS to redirect from that page, hence it's unlikely to be possible to catch that for monolith even if I make it wait 10 seconds... Cloudflare could potentially be setting cookies after "Checking your browser", those cookies could be extracted and supplied to monolith (once I implement support for said cookies, which is one of my next goals after the upcoming 2.2.0 release is out). I don't think setting user-agent would help. You could try that browser plugin SinglePage, it should save whatever you have in the DOM after the redirect, and do everything what monolith does (embed assets, resolve hrefs, etc).

Related: https://github.com/Anorov/cloudflare-scrape

**Comment by Tragen** [comment]
Thanks for your response.
I'm using SinglePage since months. ;)
I also don't have a solution how it could work.
Extracting cookies sounds like more work than it's worth but I would give it a try.

**Comment by snshn** [comment]
I'd try saving the page locally using your browser as .html + assets, and then using monolith on that -- the code in master works with file://// (e.g. `monolith local.html -o local-monolithic.html`). I'm currently preparing the aforementioned 2.2.0 release which includes that functionality.

**Comment by Tragen** [comment]
Great to hear.
That sounds like combined solution with wget or curl to spider a page.
SinglePage does that already.
I will see if I can get it running automatically.

Can you also provide a windows build?

**Comment by snshn** [comment]
As my next task for the project, I will set up the CI/CD to add builds automatically for all 3 OSes upon creating a release. ...after I'm finished with the current CSS work for 2.2.1 in #140

**Comment by snshn** [comment]
@Tragen you should be able to grab the windows binary from every release page, the latest as of now is this one: https://github.com/Y2Z/monolith/releases/tag/v2.2.3

**Comment by snshn** [comment]
Hi @Tragen,

please give this a try:

```console
chromium --headless --disable-gpu --dump-dom https://your-cloudflare-protected-url | monolith - -b https://your-cloudflare-protected-url -o test-cloudflare.html
```

**Comment by snshn** [comment]
Instructions for dealing with JavaScript (including CloudFlare's check) can be found in the latest README.md.
