### ISSUE TITLE
Wrong website conversion

### ISSUE THREAD

**Issue by rw1nkler** [Y2Z/monolith#154]
Unfortunately, I figured out that some websites are converted incorrectly. Here is an example for the [SymbiFlow project website](https://symbiflow.github.io/):

Original website:
![original](https://user-images.githubusercontent.com/52699314/78786939-d8aef500-79a9-11ea-9696-a3aff9a3e49d.png)

Converted website:
![converted](https://user-images.githubusercontent.com/52699314/78786942-db114f00-79a9-11ea-8fbe-2a481175c5af.png)

Does anyone know what might be the problem, and how to resolve it?

**Comment by snshn** [comment]
Hi there Robert,

Thanks a lot for reporting this!

Found what was causing the issue... turned out to be my boo-boo -- a bug in the CSS parser. Created a unit test and fixed it. It's now in master, will make a new release with that fix in a couple of hours, should be available on Homebrew in a day or two after that.

If you see more websites that get saved incorrectly, could you please post links here?

Thanks again!

**Comment by rw1nkler** [comment]
Thank you for your quick response! All my problem has been resolved
