### ISSUE TITLE
CLI downloads mobile version only

### ISSUE THREAD

**Issue by LiveDuo** [Y2Z/monolith#166]
I want to download the following site with Monolith. The CLI, although it works very well with some sites, there are still sites that are downloaded as mobile versions.

[https://gatsby-lander.surge.sh/](https://gatsby-lander.surge.sh/)

I already tried to loaded the page in a iframe and then saved to a file with [Monolith of the Web Chrome extension](https://github.com/rhysd/monolith-of-web) and that works just fine. The page is responsive as well!!

My use case is different though. I am required to run monolith in the backend so loading through an iframe is not an option nor the Chrome extension. 

Maybe a custom agent may trick the website to download as a desktop file? Or maybe downloading the site with puppeteer and the push the html to monolith?

Any ideas?

**Comment by snshn** [comment]
Hi Andreas,

I'm not entirely sure what you mean by "mobile version", can I ask to please clarify that? You may be referring to how some websites output different HTML based on User Agent -- there's an option in monolith to provide any user agent string you want. https://gatsby-lander.surge.sh/ got saved exactly in the same form as I'm seeing it in Firefox while I was testing. Maybe you could upload mobile and non-mobile monolithic .html files somewhere, so that I could view and compare them? Thanks.

**Comment by snshn** [comment]
It seems like that website's JavaScript redirects the browser to `/` once the page loads, which in case of opening that file locally will always redirect to this: `file:///`. I used `monolith -Ij ...` to save it without JavaScript, hence why it did not cause any issue when I opened the file.
