### ISSUE TITLE
Consider shipping amd64 binaries

### ISSUE THREAD

**Issue by colorchestra** [Y2Z/monolith#199]
Hi! 

I have noticed this subject was already touched on in https://github.com/Y2Z/monolith/issues/11, but I think the installation process can still be a bit cumbersome, especially for those who don't want to install Snap (and have its daemon running constantly just to be able to use Monolith every once in a while).

Having apt and rpm packages (and others) would be perfect imo, but just shipping the binaries that the CI builds anyway and attaching them to the Releases page could be a great start and seems like a "low hanging fruit" to make life easier for users. What do you think?

**Comment by snshn** [comment]
Hi there!

Currently the CD pipeline attaches armhf binaries to every release, they seem to work on common ARM-based devices (tested on RPi3 B+). Do you know by any chance if ARM64 supports running those binaries? I can surely make an additional CD scenario for building ARM64 if armhf is not compatible. Thanks.

**Comment by colorchestra** [comment]
Hi, thanks for getting back! To provide some clarification, what I was thinking about isn't ARM64, but AMD64. I'm not sure if that's even the correct term, but what I would like to have is a binary that runs on my normal laptop with an Intel CPU. That way I wouldn't need to install either Snap or Docker or a Rust toolchain to be able to use Monolith.

**Comment by snshn** [comment]
Oh, my bad. But the good news is: it's already been implemented, I'm glad seeing multiple requests for the same feature, means they're really valuable. [here's the CD instruction for that](https://github.com/Y2Z/monolith/blob/master/.github/workflows/cd.yml#L56)
There hasn't been a new release as of yet since that merge though, so the next release will be the first one to have a x86_64 GNUx binary attached to it. Thank you for the request! Now I'll look into AMD64, since new macs are going to use that arch.

**Comment by snshn** [comment]
[there you go](https://github.com/Y2Z/monolith/releases/tag/v2.3.0)
