### ISSUE TITLE
Vimeo Videos Dont Work

### ISSUE THREAD

**Issue by IICommitII** [Y2Z/monolith#208]
Amazing work, thank you for creating this. 

I noticed if the page has a Vimeo video embedded on the page, it won't get downloaded in HTML. I understand the goal of the tool is so the HTML page works offline too. But not having Vimeo video actually affects the completeness of the page. Maybe there is a way to download Vimeo videos too that I am not aware of? So in case when we have internet, we can watch the Vimeo video. 

Please tell us if it's possible to download pages with Vimeo video as well? Thanks again.

**Comment by trevyn** [comment]
1) You might want to check out [youtube-dl](https://github.com/ytdl-org/youtube-dl/). (it works for Vimeo and many other sites, too) 

2) youtube-dl works embedded in Rust with [pyoxidizer](https://github.com/indygreg/PyOxidizer), so it might be possible to wedge it into monolith, too.😄

**Comment by snshn** [comment]
I'll look into ways of linking Vimeo videos within saved documents, thank you for reporting this.
Not sure about embedding streaming video sources right now -- would need to establish support for plugins in order to make monolith perform custom actions for certain websites; the current codebase is a long way from there.
