### ISSUE TITLE
Blank Page when trying to pull an Earth2.io URL

### ISSUE THREAD

**Issue by kimreyio** [Y2Z/monolith#241]
Hello, I'm trying to pull down a user profile but no matter what combination I use I keep getting a blank grey page displayed in FF/Chrome/Safari.

I'm using Debian Buster, Monolith 2.4.0, and latest updated FF/Chrome/Safari.

The url is https://app.earth2.io/#profile/a87718ee-3be1-4239-a998-5c5ad07ff6d4

I've confirmed with multiple other sites that monolith is working, and also running it as root just in case.

**Comment by snshn** [comment]
That resource seems to be a JS-heavy web app. You could try to use [this browser extension](https://github.com/rhysd/monolith-of-web), or copy the HTML from the browser via web dev tools' DOM inspector, save that HTML code into a file, then do `cat file.html | monolith -b https://app.earth2.io - > file-with-assets.html`, and then _maybe_ some content will show up. I wouldn't hold my breath, since that page seems to be loading JS files asynchronously, and also likely the CORS will require you to be on the same domain. When in doubt, try [SingleFile](https://github.com/gildas-lormeau/SingleFile) (or [its browser extension](https://chrome.google.com/webstore/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle)). Please let me know what works, maybe there's a way to do this at least to some degree.

**Comment by kimreyio** [comment]
Thank you for the quick response. This is on a remote server so there isn't a web browser to access. I will move on to scraping using another application and re-displaying the data for my dashboard.

**Comment by snshn** [comment]
Try SingleFile, I'd say for saving a JS-heavy web app that'd be your best bet.
