### ISSUE TITLE
[BUG] Internet Explorer \9 hack removed from CSS

### ISSUE THREAD

**Issue by TonioGela** [Y2Z/monolith#258]
Hello! I tried to monolith a webpage, but since the result was hugely different in term of colours from the original one, I indagated a bit, and I discovered that monolith removes a "CSS hack" (whose existence was not known to me before this problem) that consists in a `\9`, hack intended for Internet Explorer described for example [here](https://stackoverflow.com/a/8004962/5281702)

In particular it transforms `div#p>svg>foreignObject>section:not(\9)` to `div#p>svg>foreignObject>section:not()` in fact inverting the `not` selector.

Sadly I'm not able to alter the css content for that page, and my intention was to use monolith in a CI, so manual intervention is not possible.

**Comment by snshn** [comment]
Hi there Antonio!

It looks like the Rust crate that monolith is using, cssparser, omits `\9` since it's technically an error in CSS syntax.  Lemme run a couple more tests, maybe I'll be able to make it put it back into the code during serialization. 🤞🏻

What is the desired behavior you're looking for, if I may ask?  Are you trying to save it as-is, or eliminating the line with the `\9` hack?

**Comment by TonioGela** [comment]
Well, in this particular case, I need to keep the `\9`, but I agree with the cssparser philosophy that CSS errors should be omitted.
Maybe it could be versatile to a command-line flag named `preserveCss` or `preserveErrors` or simply `preserve` if that is the desired behaviour. What do you think?
Btw I renew my thanks for this awesome tool ;)

**Comment by snshn** [comment]
It looks like the cssparser crate replaces `\9` with `\t` due to 0x09 being the ASCII code for the tab character.  Could you please check to see if IE[7-9] ends up treating `px\t` different from `px\9`?  I believe that's what monolith ends up saving to disk in your case.

Not sure about the CLI flag, it's quite an alphabet there already.

Glad to know people still find it useful, Monolith's almost two years old now.

**Comment by TonioGela** [comment]
I don't have windows, so it's difficult for me to test with IE[7-9], but I'll try with a VM asap.
Still, I tested the `\t` replacement in both Firefox and Chrome and while `section:(\9)` doesn't get matched `section:not(	)` (I don't know how tab renders, but there's a tab there) sadly doesn't, ending up in the same problem I had originally.

> Glad to know people still find it useful, Monolith's almost two years old now.

It's an awesome piece of software and believe me: if I knew rust better I'll be submitting a PR for this. At this moment I'm just a Scala developer trying to learn it 😓

**Comment by snshn** [comment]
I wrote some tests, it looks like by default cssparser was adding a space character after the `\9` (considered optional in the CSS spec), at least the test is passing (it preserves `(\9)` to be a `(\9)`).  Please lemme know if you can pull and build code from #260 to test it with your CI setup.  If not, please give me some time to make a new release, there're a couple of other changes I have in the backlog that I need to put in before releasing 2.5.0.  With the new version you should be able to archive those pages, if that CSS query selector hack seems to be the only issue.

**Comment by TonioGela** [comment]
I'll test it and get back to you asap, thank you!

**Comment by TonioGela** [comment]
It works! Thanks a lot! The `\9` gets copied correctly in the 2 spots it was supposed to finish! Thanks for the immediate support too! Can't wait for the next release, in the meantime, I'll use the branch version.

**Comment by snshn** [comment]
Calling it immediate is likely a stretch 😄, but I'm very glad it works now, thank you for reporting the problem.  I learned something new.
