### ISSUE TITLE
MathJax Rendering

### ISSUE THREAD

**Issue by ashish01** [Y2Z/monolith#278]
Thanks for creating this tool and selecting a great name!. In the time where everything is in cloud, its great to know that I can avoid surprises when I want to read something later.

I found an issue with pages containing math notations. e.g. https://lilianweng.github.io/lil-log/2021/05/31/contrastive-representation-learning.html contains text which is rendered as 
![image](https://user-images.githubusercontent.com/151985/125348587-48303480-e311-11eb-8f7d-1159f214d61c.png)

But in the saved monolith file its rendered as

![image](https://user-images.githubusercontent.com/151985/125348768-7f064a80-e311-11eb-9c44-5473acbc9061.png)

Does it fall within the scope of this tool to be rendered correctly?

Thanks!

**Comment by snshn** [comment]
Hi there @ashish01!

It looks like `MathJax.js` gets pulled from cloudflare, and it has JS sub-modules that must be loaded later.  Basically inside the browser it happens when you render the page and execute JS, but monolith doesn't feature a JS engine, it never renders the page, only parser the DOM, so the main JS file gets pulled while its sub-modules fail to get retrieved.

There are a few ways around that:

1. Save page as file+dir via your browser, then use monolith on that locally saved HTML file... the locally saved HTML should have HTML altered by JS, with JS sub-modules linked via DOM.  Basically `monolith -I /tmp/non-monolithic-web-page.html -o monolithic-web-page.html && rm -rf /tmp/non-monolithic-web-page.html /tmp/non-monolithic-web-page_files`.
2. Attempt to use the `-b` option, e.g. `monolith http://remote-resource.com/page.html -o temp.html && monolith -b http://cloudflare.com/lib/some-lib/modules/ temp.html -o final-result.html && rm temp.html`.  Will still require internet connection to load those JS sub-modules, but not require saving it via browser first.

SingleFile could do a better job, since that one has a built-in JS/HTML engine that renders the page.

**Comment by ashish01** [comment]
Thanks for taking time to give such a detailed reply. I did try [SingleFile](https://addons.mozilla.org/en-US/firefox/addon/single-file/) and it worked just fine. Thanks!

**Comment by snshn** [comment]
@ashish01 

Here you go dear sir:

```console
chromium --headless --disable-gpu --dump-dom https://lilianweng.github.io/lil-log/2021/05/31/contrastive-representation-learning.html | monolith - -b https://lilianweng.github.io/lil-log/2021/05/31/contrastive-representation-learning.html -o mathjax.html -Ij
```
