### ISSUE TITLE
Confusing instructions

### ISSUE THREAD

**Issue by Pound-Hash** [Y2Z/monolith#298]
Running `monolith --help` prints:

`monolith [FLAGS] [OPTIONS] <target>`

But the README on GitHub instructs:

`monolith https://lyrics.github.io/db/P/Portishead/Dummy/Roads/ -o portishead-roads-lyrics.html`

Here, the option `-o` is _after_ the `target`, not _before_ as printed from `--help`.

**Comment by RiversideRocks** [comment]
I'd suppose either would work.

**Comment by snshn** [comment]
Monolith takes only one argument, the rest is flags/options... the order is personal preference, and -o is at the end because it's hard to come up with a proper file name without seeing the target URL first.  I'll probably change it to -o "%T.html" and move before the target when automatic filename assignment feature is in place.

Thank you for the feedback!
