### ISSUE TITLE
Issue with memory usage

### ISSUE THREAD

**Issue by JokerQyou** [Y2Z/monolith#304]
Hi, I wonder if you received my email about monolith's memory usage (how monolith triggers OOM killer, to be specifically). I cannot reach you via email and other channels, thus this issue.

I'd appreciate it if you can take a look at the samples I provided. Let's continue the discussion via email.

**Comment by snshn** [comment]
Hi Joker_,

I was away from open-source work for some time, apologies for not answering your emails, was only able to access to my laptop yesterday.

OOM is a tricky thing for this program, since monolith saves the page as one file, and websites are only getting heavier and heavier, hence all those assets end up being accumulated in RAM.

**Comment by JokerQyou** [comment]
I see there is now a new issue #357 which describes the OOM issue with duplicated asset reference with more details. It's essentially the same problem with different websites. Let's track it there.
