### ISSUE TITLE
Not able to full download a webpage

### ISSUE THREAD

**Issue by aborruso** [Y2Z/monolith#319]
Hi,
first of all thank you for this great tool.

If I run

```
monolith "https://www.agenas.gov.it/covid19/web/index.php?r=site%2Ftab2" -o output.html
```

the file output does not contain the table I have in the source web page.

Is there some tips to have also this table in the monolith output? If no, I will continue to use chromium headless for this task.

Thank you again

**Comment by snshn** [comment]
Hi Andrea,

Sorry for the late reply.

This seems to be the usual issue related to JS-driven content (AJAX).  Monolith works more like a downloader (e.g. curl or wget) than a browser, downloading and embedding assets rather than running JS the way browsers do.

This works for me:

```cli
chromium --headless --disable-gpu --dump-dom "https://www.agenas.gov.it/covid19/web/index.php?r=site%2Ftab2" | monolith - -b "https://www.agenas.gov.it/covid19/web/index.php?r=site%2Ftab2" -o output.html
```

Just Chrome should also work.  Please keep in mind that this will use your Cookies from that browser unless there's a flag used for incognito mode.

I'll include instructions for similar sites into the readme file.

**Comment by aborruso** [comment]
Hi and thank you

> This seems to be the usual issue related to JS-driven content (AJAX). Monolith works more like a downloader (e.g. curl or wget) than a browser, downloading and embedding assets rather than running JS the way browsers do.

I know and I have solved my goal using `google-chrome-stable`, in your own way

> This works for me:
> 
> ```
> chromium --headless --disable-gpu --dump-dom "https://www.agenas.gov.it/covid19/web/index.php?r=site%2Ftab2" | monolith - -b "https://www.agenas.gov.it/covid19/web/index.php?r=site%2Ftab2" -o output.html
> ```

Adding to the pipe monolith is really useful.

> I'll include instructions for similar sites into the readme file.

This is a great idea.

Thank you
