### ISSUE TITLE
 Monolith cannot save 404 pages

### ISSUE THREAD

**Issue by g-saintmartin** [Y2Z/monolith#338]
Saving a 404 page

Expected behavior: Monolith writes the 404 page to target file

Actual behavior: Application quits with a status code 404

**Comment by snshn** [comment]
You're absolutely correct, @g-saintmartin 

Thank you for opening this issue.

Right away comes to mind Imgur, it has beautiful 404 pages, but trying to save https://imgur.com/gallery/doesnotexist using Monolith wouldn't work right now, because as you've mentioned, it throws an error.

There's a flag `-e`/`--ignore-errors`, it will embed content even if there was a network error, not just the first one, all subsequent assets as well.

Please let me know if it solves the issue, or if you believe it needs to work differently when the option is not specified.
