### ISSUE TITLE
Saved page is about blocked cookies

### ISSUE THREAD

**Issue by eggbean** [Y2Z/monolith#341]
When I try to save this page I just get another page about cookies being blocked:

https://www.dailytelegraph.com.au/news/nsw/lismore/the-incredible-story-of-the-real-gomez/news-story/e6427e61f047b5d63014a464e6ec750f

How can I save this page?

**Comment by snshn** [comment]
Hi Jason,

when I use the `-e` flag, I see "Potential automated action detected!" in what Monolith saves.  Interesting, haven't seen that before.
Even `chromium --headless --dump-dom` seems to be detected by that protection system.  You could try to save it as HTML+assets via the browser, and then use `monolith` on the local .index file, to get one file rather than HTML+assets.  Please let me know if that works.

**Comment by eggbean** [comment]
Yeah, that worked. Thanks. I had saved the file using Chrome's single file option which resulted in a file which is a lot smaller, but seems the same when opened in a browser. Cheers.
