### ISSUE TITLE
whole progress failed caused by  get favicon.ico

### ISSUE THREAD

**Issue by passwa11** [Y2Z/monolith#369]
```
monolith -a -v -F -o test.html https://xz.aliyun.com/t/14190
https://xz.aliyun.com/t/14190
 https://img.alicdn.com/imgextra/i1/O1CN01L12MaQ1ZwfYKk7Yrc_!!6000000003259-2-tps-900-594.png
https://xz.aliyun.com/favicon.ico (404 Not Found)

```

**Comment by snshn** [comment]
Hi there.  It looks like the missing `favicon.ico` isn't preventing the page from getting saved, but the site seems to have some kind of protection against scraping built into it, or maybe it's just heavily dependent on JS.  The HTML gets saved, but with an error inside the HTML instead of content.  You could try saving that page using Chrome as described in README, or do CTRL-S, and then run monolith against the locally saved .html file to make it one file rather than file+folder.
