### ISSUE TITLE
Can't get images from Medium links

### ISSUE THREAD

**Issue by RomeuG** [Y2Z/monolith#60]
I can't seem to get images from Medium links

Example page: https://medium.com/@cryptographer_/recon-in-2-minutes-and-got-250-easy-630ab426843

Command used: `monolith -kjs https://medium.com/@cryptographer_/recon-in-2-minutes-and-got-250-easy-630ab426843`

**Comment by snshn** [comment]
Hello @RomeuG!

Medium seems to be using JS in order to lazy-load images. Same JS redirects the user away to some 404 template within the main content box. Go figure.

I believe you could have some luck using https://github.com/gildas-lormeau/SingleFile either as a browser plug-in or via CLI, I believe it should support Medium. I'll need to revamp monolith to use a headless browser underneath in order to embed assets (pulling them directly from that said browser's memory). It's tricky af but we'll get there one day, until then I hope SingleFile does the job for you!

**Comment by RomeuG** [comment]
Thank you for your response! :-)

**Comment by snshn** [comment]
The latest version (2.4.1) embeds images found within NOSCRIPT tags. That technically makes it save images from Medium, but they're only visible when JS is turned off. I'm planning to add a `-n` option for "unwrapping" NOSCRIPT tags in the next release, that should resolve this issue completely.

**Comment by RomeuG** [comment]
That's great! Good job! :-)
