### ISSUE TITLE
Add support for `poster` attribute of `video` element

### ISSUE THREAD

**Issue by amirouche** [Y2Z/monolith#62]
As of right now, packing a page with a video element does not embed video (ok) but it does not embed the `poster` attribute making the page unreadable.

Here is an example for `monolith https://hyper.dev > out.html`:

```html
...
IG1hcmdpbi10b3A6IDE1cHg7Cn0KCgojcm9vdC5pbmRleCB1bCA+IGxpIHsKICAgIHBhZGRpbmc6IDVweDsKfQoKI2Rpc3F1c190aHJlYWQgewogICAgd2
lkdGg6IDY2NnB4OwogICAgbWFyZ2luOiBhdXRvOwp9CgpibG9ja3F1b3RlIHsKICAgIHBhZGRpbmc6IDE1cHg7CiAgICBiYWNrZ3JvdW5kOiBoc2xhKDAs
IDAlLCAxMDAlLCAwLjIpOwogICAgbWFyZ2luLXRvcDogMTBweCAhaW1wb3J0YW50OwogICAgbWFyZ2luLWJvdHRvbTogMTBweCAhaW1wb3J0YW50Owp9Cg
pwIHsKICAgIG1hcmdpbi10b3A6IDEwcHggIWltcG9ydGFudDsKICAgIG1hcmdpbi1ib3R0b206IDEwcHggIWltcG9ydGFudDsKfQo=">
        <title></title>
    </head>
    <body>
        <div id="background">
            <video autoplay="" loop="" poster="/static/video/poster.jpeg">
                <source src="/static/video/space.mp4" type="video/mp4">
                <source src="/static/video/space.webm" type="video/webm">
            </video>
        </div>
        <div id="overlay">
...
```

**Comment by snshn** [comment]
Hello @amirouche and thank you for submitting the issue!

I've added support for the poster attribute, if you build the latest version of monolith it should work for that page. As a side note, if that particular resource is saved with `-i` it will still end up being white-on-white. You may want to add `html { background-color: #000; }` to your CSS in order to prevent this from happening.

**Comment by amirouche** [comment]
Tx for the quick improvement.

> You may want to add html { background-color: #000; } to your CSS in order to prevent that from happening.

I must! Thanks for hint.
